<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f2fa5b4e-b7a5-4511-880a-5e02f8e346cf</UserSecretsId>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ticketa.Core\Ticketa.Core.csproj" />
    <ProjectReference Include="..\Ticketa.Infrastructure\Ticketa.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Properties\PublishProfiles\ticketa.runasp.net-WebDeploy.publishSettings" />
    <None Remove="Properties\PublishProfiles\Ticketa.pubxml" />
  </ItemGroup>

</Project>
